[{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module '@/components/SignaturePad' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 5,
	"startColumn": 26,
	"endLineNumber": 5,
	"endColumn": 53,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module '@/components/LeavePDFPreview' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 29,
	"endLineNumber": 6,
	"endColumn": 59,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'props'.",
	"source": "ts",
	"startLineNumber": 213,
	"startColumn": 54,
	"endLineNumber": 213,
	"endColumn": 59,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "17008",
	"severity": 8,
	"message": "JSX element 'div' has no corresponding closing tag.",
	"source": "ts",
	"startLineNumber": 823,
	"startColumn": 4,
	"endLineNumber": 823,
	"endColumn": 7,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'showSigPad'.",
	"source": "ts",
	"startLineNumber": 825,
	"startColumn": 6,
	"endLineNumber": 825,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'sigUrl'.",
	"source": "ts",
	"startLineNumber": 827,
	"startColumn": 21,
	"endLineNumber": 827,
	"endColumn": 27,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'dataUrl' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 828,
	"startColumn": 24,
	"endLineNumber": 828,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setSigUrl'.",
	"source": "ts",
	"startLineNumber": 829,
	"startColumn": 11,
	"endLineNumber": 829,
	"endColumn": 20,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowSigPad'.",
	"source": "ts",
	"startLineNumber": 830,
	"startColumn": 11,
	"endLineNumber": 830,
	"endColumn": 24,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowSigPad'.",
	"source": "ts",
	"startLineNumber": 836,
	"startColumn": 24,
	"endLineNumber": 836,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'showPreview'.",
	"source": "ts",
	"startLineNumber": 841,
	"startColumn": 6,
	"endLineNumber": 841,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 841,
	"startColumn": 21,
	"endLineNumber": 841,
	"endColumn": 35,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 846,
	"startColumn": 22,
	"endLineNumber": 846,
	"endColumn": 36,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 847,
	"startColumn": 62,
	"endLineNumber": 847,
	"endColumn": 76,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 848,
	"startColumn": 27,
	"endLineNumber": 848,
	"endColumn": 41,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 849,
	"startColumn": 22,
	"endLineNumber": 849,
	"endColumn": 36,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 850,
	"startColumn": 20,
	"endLineNumber": 850,
	"endColumn": 34,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 851,
	"startColumn": 17,
	"endLineNumber": 851,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 852,
	"startColumn": 20,
	"endLineNumber": 852,
	"endColumn": 34,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingPayload'.",
	"source": "ts",
	"startLineNumber": 853,
	"startColumn": 19,
	"endLineNumber": 853,
	"endColumn": 33,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'sigUrl'.",
	"source": "ts",
	"startLineNumber": 854,
	"startColumn": 25,
	"endLineNumber": 854,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'sigUrl'.",
	"source": "ts",
	"startLineNumber": 857,
	"startColumn": 23,
	"endLineNumber": 857,
	"endColumn": 29,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'sigUrl'.",
	"source": "ts",
	"startLineNumber": 858,
	"startColumn": 25,
	"endLineNumber": 858,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'confirmSubmit'.",
	"source": "ts",
	"startLineNumber": 859,
	"startColumn": 20,
	"endLineNumber": 859,
	"endColumn": 33,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowPreview'.",
	"source": "ts",
	"startLineNumber": 860,
	"startColumn": 25,
	"endLineNumber": 860,
	"endColumn": 39,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setShowSigPad'.",
	"source": "ts",
	"startLineNumber": 861,
	"startColumn": 34,
	"endLineNumber": 861,
	"endColumn": 47,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 986,
	"startColumn": 1,
	"endLineNumber": 986,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 989,
	"startColumn": 41,
	"endLineNumber": 989,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 989,
	"startColumn": 55,
	"endLineNumber": 989,
	"endColumn": 56,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 3,
	"endLineNumber": 990,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'LeaveRequest' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 52,
	"endLineNumber": 990,
	"endColumn": 64,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 64,
	"endLineNumber": 990,
	"endColumn": 65,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 990,
	"startColumn": 66,
	"endLineNumber": 990,
	"endColumn": 67,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 992,
	"startColumn": 52,
	"endLineNumber": 992,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 992,
	"startColumn": 69,
	"endLineNumber": 992,
	"endColumn": 70,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'LeaveType' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 993,
	"startColumn": 52,
	"endLineNumber": 993,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 993,
	"startColumn": 62,
	"endLineNumber": 993,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 993,
	"startColumn": 69,
	"endLineNumber": 993,
	"endColumn": 70,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'LeaveStatus' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 994,
	"startColumn": 52,
	"endLineNumber": 994,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 994,
	"startColumn": 64,
	"endLineNumber": 994,
	"endColumn": 65,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 994,
	"startColumn": 71,
	"endLineNumber": 994,
	"endColumn": 72,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 995,
	"startColumn": 52,
	"endLineNumber": 995,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 995,
	"startColumn": 86,
	"endLineNumber": 995,
	"endColumn": 87,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 998,
	"startColumn": 41,
	"endLineNumber": 998,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 999,
	"startColumn": 21,
	"endLineNumber": 999,
	"endColumn": 22,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1000,
	"startColumn": 13,
	"endLineNumber": 1000,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ascending'.",
	"source": "ts",
	"startLineNumber": 1003,
	"startColumn": 30,
	"endLineNumber": 1003,
	"endColumn": 39,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1003,
	"startColumn": 39,
	"endLineNumber": 1003,
	"endColumn": 40,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1003,
	"startColumn": 47,
	"endLineNumber": 1003,
	"endColumn": 48,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1006,
	"startColumn": 3,
	"endLineNumber": 1006,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'BarChart'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 18,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 18,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 23,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 30,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 37,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 52,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 61,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 10,
	"endLineNumber": 1009,
	"endColumn": 69,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Bar'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 20,
	"endLineNumber": 1009,
	"endColumn": 23,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'XAxis'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 25,
	"endLineNumber": 1009,
	"endColumn": 30,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'YAxis'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 32,
	"endLineNumber": 1009,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'CartesianGrid'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 39,
	"endLineNumber": 1009,
	"endColumn": 52,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Tooltip'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 54,
	"endLineNumber": 1009,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Legend'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 63,
	"endLineNumber": 1009,
	"endColumn": 69,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ResponsiveContainer'.",
	"source": "ts",
	"startLineNumber": 1009,
	"startColumn": 71,
	"endLineNumber": 1009,
	"endColumn": 90,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1013,
	"startColumn": 5,
	"endLineNumber": 1013,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1013,
	"startColumn": 8,
	"endLineNumber": 1013,
	"endColumn": 9,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1013,
	"startColumn": 52,
	"endLineNumber": 1013,
	"endColumn": 53,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1014,
	"startColumn": 5,
	"endLineNumber": 1014,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1014,
	"startColumn": 8,
	"endLineNumber": 1014,
	"endColumn": 9,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1014,
	"startColumn": 53,
	"endLineNumber": 1014,
	"endColumn": 54,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1015,
	"startColumn": 5,
	"endLineNumber": 1015,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1015,
	"startColumn": 8,
	"endLineNumber": 1015,
	"endColumn": 9,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1015,
	"startColumn": 54,
	"endLineNumber": 1015,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1016,
	"startColumn": 5,
	"endLineNumber": 1016,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1016,
	"startColumn": 8,
	"endLineNumber": 1016,
	"endColumn": 9,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1016,
	"startColumn": 53,
	"endLineNumber": 1016,
	"endColumn": 54,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1025,
	"startColumn": 51,
	"endLineNumber": 1025,
	"endColumn": 52,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1027,
	"startColumn": 3,
	"endLineNumber": 1027,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1027,
	"startColumn": 24,
	"endLineNumber": 1027,
	"endColumn": 25,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1028,
	"startColumn": 24,
	"endLineNumber": 1028,
	"endColumn": 25,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1029,
	"startColumn": 40,
	"endLineNumber": 1029,
	"endColumn": 41,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1030,
	"startColumn": 5,
	"endLineNumber": 1030,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1033,
	"startColumn": 3,
	"endLineNumber": 1033,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'month'.",
	"source": "ts",
	"startLineNumber": 1035,
	"startColumn": 5,
	"endLineNumber": 1035,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1035,
	"startColumn": 5,
	"endLineNumber": 1035,
	"endColumn": 10,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ลาป่วย'.",
	"source": "ts",
	"startLineNumber": 1036,
	"startColumn": 5,
	"endLineNumber": 1036,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1036,
	"startColumn": 11,
	"endLineNumber": 1036,
	"endColumn": 12,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1036,
	"startColumn": 36,
	"endLineNumber": 1036,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1036,
	"startColumn": 76,
	"endLineNumber": 1036,
	"endColumn": 77,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1037,
	"startColumn": 36,
	"endLineNumber": 1037,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1037,
	"startColumn": 80,
	"endLineNumber": 1037,
	"endColumn": 81,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1038,
	"startColumn": 36,
	"endLineNumber": 1038,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1038,
	"startColumn": 80,
	"endLineNumber": 1038,
	"endColumn": 81,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1039,
	"startColumn": 36,
	"endLineNumber": 1039,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1039,
	"startColumn": 107,
	"endLineNumber": 1039,
	"endColumn": 108,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1040,
	"startColumn": 3,
	"endLineNumber": 1040,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1041,
	"startColumn": 1,
	"endLineNumber": 1041,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'tab'.",
	"source": "ts",
	"startLineNumber": 1044,
	"startColumn": 2,
	"endLineNumber": 1044,
	"endColumn": 5,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ResponsiveContainer'.",
	"source": "ts",
	"startLineNumber": 1049,
	"startColumn": 6,
	"endLineNumber": 1049,
	"endColumn": 25,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'BarChart'.",
	"source": "ts",
	"startLineNumber": 1050,
	"startColumn": 8,
	"endLineNumber": 1050,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'graphData'.",
	"source": "ts",
	"startLineNumber": 1050,
	"startColumn": 23,
	"endLineNumber": 1050,
	"endColumn": 32,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'CartesianGrid'.",
	"source": "ts",
	"startLineNumber": 1051,
	"startColumn": 10,
	"endLineNumber": 1051,
	"endColumn": 23,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'XAxis'.",
	"source": "ts",
	"startLineNumber": 1052,
	"startColumn": 10,
	"endLineNumber": 1052,
	"endColumn": 15,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'YAxis'.",
	"source": "ts",
	"startLineNumber": 1053,
	"startColumn": 10,
	"endLineNumber": 1053,
	"endColumn": 15,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Tooltip'.",
	"source": "ts",
	"startLineNumber": 1054,
	"startColumn": 10,
	"endLineNumber": 1054,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Legend'.",
	"source": "ts",
	"startLineNumber": 1058,
	"startColumn": 10,
	"endLineNumber": 1058,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Bar'.",
	"source": "ts",
	"startLineNumber": 1059,
	"startColumn": 10,
	"endLineNumber": 1059,
	"endColumn": 13,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Bar'.",
	"source": "ts",
	"startLineNumber": 1060,
	"startColumn": 10,
	"endLineNumber": 1060,
	"endColumn": 13,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Bar'.",
	"source": "ts",
	"startLineNumber": 1061,
	"startColumn": 10,
	"endLineNumber": 1061,
	"endColumn": 13,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'Bar'.",
	"source": "ts",
	"startLineNumber": 1062,
	"startColumn": 10,
	"endLineNumber": 1062,
	"endColumn": 13,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'BarChart'.",
	"source": "ts",
	"startLineNumber": 1063,
	"startColumn": 9,
	"endLineNumber": 1063,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ResponsiveContainer'.",
	"source": "ts",
	"startLineNumber": 1064,
	"startColumn": 7,
	"endLineNumber": 1064,
	"endColumn": 26,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'graphData'.",
	"source": "ts",
	"startLineNumber": 1069,
	"startColumn": 36,
	"endLineNumber": 1069,
	"endColumn": 45,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1069,
	"startColumn": 54,
	"endLineNumber": 1069,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'd' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1069,
	"startColumn": 56,
	"endLineNumber": 1069,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'graphData'.",
	"source": "ts",
	"startLineNumber": 1070,
	"startColumn": 36,
	"endLineNumber": 1070,
	"endColumn": 45,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1070,
	"startColumn": 54,
	"endLineNumber": 1070,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'd' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1070,
	"startColumn": 56,
	"endLineNumber": 1070,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'graphData'.",
	"source": "ts",
	"startLineNumber": 1071,
	"startColumn": 36,
	"endLineNumber": 1071,
	"endColumn": 45,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1071,
	"startColumn": 54,
	"endLineNumber": 1071,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'd' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1071,
	"startColumn": 56,
	"endLineNumber": 1071,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'graphData'.",
	"source": "ts",
	"startLineNumber": 1072,
	"startColumn": 36,
	"endLineNumber": 1072,
	"endColumn": 45,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 's' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1072,
	"startColumn": 54,
	"endLineNumber": 1072,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'd' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1072,
	"startColumn": 56,
	"endLineNumber": 1072,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1083,
	"startColumn": 17,
	"endLineNumber": 1083,
	"endColumn": 18,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'loadAll'.",
	"source": "ts",
	"startLineNumber": 1083,
	"startColumn": 21,
	"endLineNumber": 1083,
	"endColumn": 28,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1083,
	"startColumn": 30,
	"endLineNumber": 1083,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1083,
	"startColumn": 32,
	"endLineNumber": 1083,
	"endColumn": 33,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1086,
	"startColumn": 5,
	"endLineNumber": 1086,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1086,
	"startColumn": 34,
	"endLineNumber": 1086,
	"endColumn": 35,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'slot'.",
	"source": "ts",
	"startLineNumber": 1087,
	"startColumn": 41,
	"endLineNumber": 1087,
	"endColumn": 45,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1087,
	"startColumn": 55,
	"endLineNumber": 1087,
	"endColumn": 56,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1087,
	"startColumn": 64,
	"endLineNumber": 1087,
	"endColumn": 65,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1093,
	"startColumn": 41,
	"endLineNumber": 1093,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1095,
	"startColumn": 30,
	"endLineNumber": 1095,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'error'.",
	"source": "ts",
	"startLineNumber": 1096,
	"startColumn": 13,
	"endLineNumber": 1096,
	"endColumn": 18,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'error'.",
	"source": "ts",
	"startLineNumber": 1097,
	"startColumn": 31,
	"endLineNumber": 1097,
	"endColumn": 36,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1097,
	"startColumn": 45,
	"endLineNumber": 1097,
	"endColumn": 46,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1097,
	"startColumn": 55,
	"endLineNumber": 1097,
	"endColumn": 56,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'req'.",
	"source": "ts",
	"startLineNumber": 1104,
	"startColumn": 9,
	"endLineNumber": 1104,
	"endColumn": 12,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'statusLabel'.",
	"source": "ts",
	"startLineNumber": 1105,
	"startColumn": 31,
	"endLineNumber": 1105,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'id'.",
	"source": "ts",
	"startLineNumber": 1106,
	"startColumn": 9,
	"endLineNumber": 1106,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1107,
	"startColumn": 8,
	"endLineNumber": 1107,
	"endColumn": 9,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1108,
	"startColumn": 5,
	"endLineNumber": 1108,
	"endColumn": 6,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1111,
	"startColumn": 3,
	"endLineNumber": 1111,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1113,
	"startColumn": 36,
	"endLineNumber": 1113,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1115,
	"startColumn": 60,
	"endLineNumber": 1115,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'approved'.",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 7,
	"endLineNumber": 1116,
	"endColumn": 15,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 15,
	"endLineNumber": 1116,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 33,
	"endLineNumber": 1116,
	"endColumn": 34,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1116,
	"startColumn": 97,
	"endLineNumber": 1116,
	"endColumn": 98,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1117,
	"startColumn": 33,
	"endLineNumber": 1117,
	"endColumn": 34,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1118,
	"startColumn": 5,
	"endLineNumber": 1118,
	"endColumn": 6,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'LeaveType' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 15,
	"endLineNumber": 1119,
	"endColumn": 24,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 24,
	"endLineNumber": 1119,
	"endColumn": 25,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'approved'.",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 28,
	"endLineNumber": 1119,
	"endColumn": 36,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 36,
	"endLineNumber": 1119,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 62,
	"endLineNumber": 1119,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 63,
	"endLineNumber": 1119,
	"endColumn": 64,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1121,
	"startColumn": 43,
	"endLineNumber": 1121,
	"endColumn": 44,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1122,
	"startColumn": 43,
	"endLineNumber": 1122,
	"endColumn": 44,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1126,
	"startColumn": 42,
	"endLineNumber": 1126,
	"endColumn": 43,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1127,
	"startColumn": 5,
	"endLineNumber": 1127,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1132,
	"startColumn": 3,
	"endLineNumber": 1132,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1135,
	"startColumn": 5,
	"endLineNumber": 1135,
	"endColumn": 7,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1139,
	"startColumn": 3,
	"endLineNumber": 1139,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1142,
	"startColumn": 7,
	"endLineNumber": 1142,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1142,
	"startColumn": 10,
	"endLineNumber": 1142,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1142,
	"startColumn": 55,
	"endLineNumber": 1142,
	"endColumn": 56,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1143,
	"startColumn": 7,
	"endLineNumber": 1143,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1143,
	"startColumn": 10,
	"endLineNumber": 1143,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1143,
	"startColumn": 56,
	"endLineNumber": 1143,
	"endColumn": 57,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'key'.",
	"source": "ts",
	"startLineNumber": 1144,
	"startColumn": 7,
	"endLineNumber": 1144,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1144,
	"startColumn": 10,
	"endLineNumber": 1144,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1144,
	"startColumn": 57,
	"endLineNumber": 1144,
	"endColumn": 58,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'summaryByType'.",
	"source": "ts",
	"startLineNumber": 1175,
	"startColumn": 25,
	"endLineNumber": 1175,
	"endColumn": 38,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'TABS'.",
	"source": "ts",
	"startLineNumber": 1194,
	"startColumn": 10,
	"endLineNumber": 1194,
	"endColumn": 14,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'key' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1194,
	"startColumn": 22,
	"endLineNumber": 1194,
	"endColumn": 25,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'label' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1194,
	"startColumn": 27,
	"endLineNumber": 1194,
	"endColumn": 32,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7031",
	"severity": 8,
	"message": "Binding element 'icon' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1194,
	"startColumn": 34,
	"endLineNumber": 1194,
	"endColumn": 38,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setTab'.",
	"source": "ts",
	"startLineNumber": 1195,
	"startColumn": 44,
	"endLineNumber": 1195,
	"endColumn": 50,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'tab'.",
	"source": "ts",
	"startLineNumber": 1196,
	"startColumn": 127,
	"endLineNumber": 1196,
	"endColumn": 130,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingList'.",
	"source": "ts",
	"startLineNumber": 1198,
	"startColumn": 35,
	"endLineNumber": 1198,
	"endColumn": 46,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingList'.",
	"source": "ts",
	"startLineNumber": 1199,
	"startColumn": 106,
	"endLineNumber": 1199,
	"endColumn": 117,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'tab'.",
	"source": "ts",
	"startLineNumber": 1206,
	"startColumn": 8,
	"endLineNumber": 1206,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingList'.",
	"source": "ts",
	"startLineNumber": 1209,
	"startColumn": 15,
	"endLineNumber": 1209,
	"endColumn": 26,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'pendingList'.",
	"source": "ts",
	"startLineNumber": 1211,
	"startColumn": 17,
	"endLineNumber": 1211,
	"endColumn": 28,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'r' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1211,
	"startColumn": 33,
	"endLineNumber": 1211,
	"endColumn": 34,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Record<LeaveType, { label: string; icon: string; quota: number | null; }>'.",
	"source": "ts",
	"startLineNumber": 1212,
	"startColumn": 32,
	"endLineNumber": 1212,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'mySlot'.",
	"source": "ts",
	"startLineNumber": 1214,
	"startColumn": 32,
	"endLineNumber": 1214,
	"endColumn": 38,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'handleApprove'.",
	"source": "ts",
	"startLineNumber": 1249,
	"startColumn": 48,
	"endLineNumber": 1249,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'handleApprove'.",
	"source": "ts",
	"startLineNumber": 1253,
	"startColumn": 48,
	"endLineNumber": 1253,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'tab'.",
	"source": "ts",
	"startLineNumber": 1273,
	"startColumn": 8,
	"endLineNumber": 1273,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'filterStatus'.",
	"source": "ts",
	"startLineNumber": 1283,
	"startColumn": 28,
	"endLineNumber": 1283,
	"endColumn": 40,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setFilterStatus'.",
	"source": "ts",
	"startLineNumber": 1283,
	"startColumn": 57,
	"endLineNumber": 1283,
	"endColumn": 72,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'historyList'.",
	"source": "ts",
	"startLineNumber": 1293,
	"startColumn": 17,
	"endLineNumber": 1293,
	"endColumn": 28,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'historyList'.",
	"source": "ts",
	"startLineNumber": 1297,
	"startColumn": 20,
	"endLineNumber": 1297,
	"endColumn": 31,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'r' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1297,
	"startColumn": 36,
	"endLineNumber": 1297,
	"endColumn": 37,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7053",
	"severity": 8,
	"message": "Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'Record<LeaveType, { label: string; icon: string; quota: number | null; }>'.",
	"source": "ts",
	"startLineNumber": 1298,
	"startColumn": 37,
	"endLineNumber": 1298,
	"endColumn": 68,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'tab'.",
	"source": "ts",
	"startLineNumber": 1321,
	"startColumn": 8,
	"endLineNumber": 1321,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'officialList'.",
	"source": "ts",
	"startLineNumber": 1324,
	"startColumn": 15,
	"endLineNumber": 1324,
	"endColumn": 27,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'officialList'.",
	"source": "ts",
	"startLineNumber": 1326,
	"startColumn": 17,
	"endLineNumber": 1326,
	"endColumn": 29,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "7006",
	"severity": 8,
	"message": "Parameter 'r' implicitly has an 'any' type.",
	"source": "ts",
	"startLineNumber": 1326,
	"startColumn": 34,
	"endLineNumber": 1326,
	"endColumn": 35,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1353,
	"startColumn": 1,
	"endLineNumber": 1353,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1357,
	"startColumn": 3,
	"endLineNumber": 1357,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'UserProfile' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 1358,
	"startColumn": 50,
	"endLineNumber": 1358,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1358,
	"startColumn": 62,
	"endLineNumber": 1358,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1358,
	"startColumn": 68,
	"endLineNumber": 1358,
	"endColumn": 69,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'ApproverInfo' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 1359,
	"startColumn": 50,
	"endLineNumber": 1359,
	"endColumn": 62,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1359,
	"startColumn": 62,
	"endLineNumber": 1359,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1359,
	"startColumn": 64,
	"endLineNumber": 1359,
	"endColumn": 65,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2693",
	"severity": 8,
	"message": "'UserProfile' only refers to a type, but is being used as a value here.",
	"source": "ts",
	"startLineNumber": 1360,
	"startColumn": 50,
	"endLineNumber": 1360,
	"endColumn": 61,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1003",
	"severity": 8,
	"message": "Identifier expected.",
	"source": "ts",
	"startLineNumber": 1360,
	"startColumn": 61,
	"endLineNumber": 1360,
	"endColumn": 62,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1360,
	"startColumn": 63,
	"endLineNumber": 1360,
	"endColumn": 64,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1363,
	"startColumn": 17,
	"endLineNumber": 1363,
	"endColumn": 18,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1364,
	"startColumn": 5,
	"endLineNumber": 1364,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1364,
	"startColumn": 28,
	"endLineNumber": 1364,
	"endColumn": 29,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 7,
	"endLineNumber": 1365,
	"endColumn": 12,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 15,
	"endLineNumber": 1365,
	"endColumn": 19,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 19,
	"endLineNumber": 1365,
	"endColumn": 20,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 27,
	"endLineNumber": 1365,
	"endColumn": 28,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 38,
	"endLineNumber": 1365,
	"endColumn": 39,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1365,
	"startColumn": 40,
	"endLineNumber": 1365,
	"endColumn": 41,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1366,
	"startColumn": 41,
	"endLineNumber": 1366,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1366,
	"startColumn": 51,
	"endLineNumber": 1366,
	"endColumn": 52,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1387,
	"startColumn": 13,
	"endLineNumber": 1387,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1394,
	"startColumn": 9,
	"endLineNumber": 1394,
	"endColumn": 14,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2311",
	"severity": 8,
	"message": "Cannot find name 'await'. Did you mean to write this in an async function?",
	"source": "ts",
	"startLineNumber": 1401,
	"startColumn": 11,
	"endLineNumber": 1401,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'authUser'.",
	"source": "ts",
	"startLineNumber": 1401,
	"startColumn": 67,
	"endLineNumber": 1401,
	"endColumn": 75,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1401,
	"startColumn": 92,
	"endLineNumber": 1401,
	"endColumn": 96,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1401,
	"startColumn": 108,
	"endLineNumber": 1401,
	"endColumn": 109,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1402,
	"startColumn": 9,
	"endLineNumber": 1402,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1403,
	"startColumn": 7,
	"endLineNumber": 1403,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'email'.",
	"source": "ts",
	"startLineNumber": 1406,
	"startColumn": 66,
	"endLineNumber": 1406,
	"endColumn": 71,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1406,
	"startColumn": 72,
	"endLineNumber": 1406,
	"endColumn": 73,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1407,
	"startColumn": 7,
	"endLineNumber": 1407,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1410,
	"startColumn": 9,
	"endLineNumber": 1410,
	"endColumn": 14,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2609",
	"severity": 8,
	"message": "JSX spread child must be an array type.",
	"source": "ts",
	"startLineNumber": 1410,
	"startColumn": 38,
	"endLineNumber": 1412,
	"endColumn": 20,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1411,
	"startColumn": 15,
	"endLineNumber": 1411,
	"endColumn": 19,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'full_name'.",
	"source": "ts",
	"startLineNumber": 1412,
	"startColumn": 11,
	"endLineNumber": 1412,
	"endColumn": 20,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1412,
	"startColumn": 20,
	"endLineNumber": 1412,
	"endColumn": 21,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1413,
	"startColumn": 17,
	"endLineNumber": 1413,
	"endColumn": 21,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1413,
	"startColumn": 51,
	"endLineNumber": 1413,
	"endColumn": 55,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1414,
	"startColumn": 9,
	"endLineNumber": 1414,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1420,
	"startColumn": 11,
	"endLineNumber": 1420,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1424,
	"startColumn": 9,
	"endLineNumber": 1424,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'setSavedSignature'.",
	"source": "ts",
	"startLineNumber": 1429,
	"startColumn": 3,
	"endLineNumber": 1429,
	"endColumn": 20,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'data'.",
	"source": "ts",
	"startLineNumber": 1429,
	"startColumn": 22,
	"endLineNumber": 1429,
	"endColumn": 26,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1429,
	"startColumn": 49,
	"endLineNumber": 1429,
	"endColumn": 50,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1430,
	"startColumn": 1,
	"endLineNumber": 1430,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type '{ user: UserProfile; approvers: ApproverInfo[]; allTeachers: UserProfile[]; savedSignature: any; }' is not assignable to type 'IntrinsicAttributes & { user: UserProfile; approvers: ApproverInfo[]; allTeachers: UserProfile[]; }'.\n  Property 'savedSignature' does not exist on type 'IntrinsicAttributes & { user: UserProfile; approvers: ApproverInfo[]; allTeachers: UserProfile[]; }'.",
	"source": "ts",
	"startLineNumber": 1437,
	"startColumn": 3,
	"endLineNumber": 1437,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'savedSignature'.",
	"source": "ts",
	"startLineNumber": 1437,
	"startColumn": 19,
	"endLineNumber": 1437,
	"endColumn": 33,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1443,
	"startColumn": 11,
	"endLineNumber": 1443,
	"endColumn": 16,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1382",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'>'}` or `&gt;`?",
	"source": "ts",
	"startLineNumber": 1451,
	"startColumn": 62,
	"endLineNumber": 1451,
	"endColumn": 63,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2609",
	"severity": 8,
	"message": "JSX spread child must be an array type.",
	"source": "ts",
	"startLineNumber": 1451,
	"startColumn": 65,
	"endLineNumber": 1453,
	"endColumn": 22,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'a'.",
	"source": "ts",
	"startLineNumber": 1452,
	"startColumn": 16,
	"endLineNumber": 1452,
	"endColumn": 17,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2695",
	"severity": 8,
	"message": "Left side of comma operator is unused and has no side effects.",
	"source": "ts",
	"startLineNumber": 1452,
	"startColumn": 16,
	"endLineNumber": 1452,
	"endColumn": 17,
	"modelVersionId": 260,
	"tags": [
		1
	],
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'full_name'.",
	"source": "ts",
	"startLineNumber": 1453,
	"startColumn": 13,
	"endLineNumber": 1453,
	"endColumn": 22,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'}' expected.",
	"source": "ts",
	"startLineNumber": 1453,
	"startColumn": 22,
	"endLineNumber": 1453,
	"endColumn": 23,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'a'.",
	"source": "ts",
	"startLineNumber": 1453,
	"startColumn": 42,
	"endLineNumber": 1453,
	"endColumn": 43,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'a'.",
	"source": "ts",
	"startLineNumber": 1453,
	"startColumn": 64,
	"endLineNumber": 1453,
	"endColumn": 65,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1454,
	"startColumn": 11,
	"endLineNumber": 1454,
	"endColumn": 12,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1456,
	"startColumn": 9,
	"endLineNumber": 1456,
	"endColumn": 10,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1457,
	"startColumn": 7,
	"endLineNumber": 1457,
	"endColumn": 8,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1459,
	"startColumn": 5,
	"endLineNumber": 1459,
	"endColumn": 6,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1461,
	"startColumn": 3,
	"endLineNumber": 1461,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1464,
	"startColumn": 5,
	"endLineNumber": 1464,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1469,
	"startColumn": 3,
	"endLineNumber": 1469,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "Expression expected.",
	"source": "ts",
	"startLineNumber": 1471,
	"startColumn": 5,
	"endLineNumber": 1471,
	"endColumn": 11,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1476,
	"startColumn": 3,
	"endLineNumber": 1476,
	"endColumn": 4,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'router'.",
	"source": "ts",
	"startLineNumber": 1492,
	"startColumn": 36,
	"endLineNumber": 1492,
	"endColumn": 42,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'isTeacher'.",
	"source": "ts",
	"startLineNumber": 1502,
	"startColumn": 82,
	"endLineNumber": 1502,
	"endColumn": 91,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'roleLabel'.",
	"source": "ts",
	"startLineNumber": 1503,
	"startColumn": 14,
	"endLineNumber": 1503,
	"endColumn": 23,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'isTeacher'.",
	"source": "ts",
	"startLineNumber": 1510,
	"startColumn": 10,
	"endLineNumber": 1510,
	"endColumn": 19,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'AdminDashboard'.",
	"source": "ts",
	"startLineNumber": 1513,
	"startColumn": 12,
	"endLineNumber": 1513,
	"endColumn": 26,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1381",
	"severity": 8,
	"message": "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?",
	"source": "ts",
	"startLineNumber": 1518,
	"startColumn": 1,
	"endLineNumber": 1518,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
},{
	"resource": "/d:/WEB/school-app/app/leave/page.tsx",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "'</' expected.",
	"source": "ts",
	"startLineNumber": 1518,
	"startColumn": 2,
	"endLineNumber": 1518,
	"endColumn": 2,
	"modelVersionId": 260,
	"origin": "extHost1"
}]